# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-27 21:10:06

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Extract categories and values
    categories = data_raw['Category'].tolist()
    true_counts = data_raw['True_Count'].tolist()
    false_counts = data_raw['False_Count'].tolist()
    
    # Create grouped bar chart
    fig = go.Figure(data=[
        go.Bar(name='True_Count', x=categories, y=true_counts, marker_color='royalblue'),
        go.Bar(name='False_Count', x=categories, y=false_counts, marker_color='orange')
    ])
    
    # Update layout for grouped bars and titles
    fig.update_layout(
        barmode='group',
        title="Count of Transmission Manual and Fuel Type Categories by True and False Counts",
        xaxis_title="Category",
        yaxis_title="Count",
        legend_title_text="Count Type"
    )
    
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    
    return fig_dict